name: bgnns
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - icu=58.2
  - idna=3.4
  - importlib_metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - openssl=3.0.9
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.29.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=67.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - black==23.3.0
      - cachetools==5.3.1
      - chex==0.1.81
      - click==8.1.3
      - clu==0.0.9
      - contextlib2==21.6.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - dm-tree==0.1.8
      - etils==1.3.0
      - flatbuffers==23.5.26
      - flax==0.6.11
      - fonttools==4.40.0
      - gast==0.4.0
      - google-auth==2.21.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.56.0
      - h5py==3.9.0
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - jax==0.4.13
      - jaxlib==0.4.13+cuda11.cudnn86
      - joblib==1.3.1
      - jraph==0.0.6.dev0
      - jupyter-black==0.3.4
      - keras==2.13.1
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - markdown==3.4.3
      - markdown-it-py==3.0.0
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - msgpack==1.0.5
      - multipledispatch==1.0.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nodejs==0.1.1
      - npm==0.1.1
      - numpy==1.24.3
      - numpyro==0.12.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optax==0.1.5
      - optional-django==0.1.0
      - orbax-checkpoint==0.2.7
      - pandas==2.0.3
      - pathspec==0.11.1
      - pillow==10.0.0
      - protobuf==4.23.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.0
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rsa==4.9
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - tensorstore==0.1.40
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tokenize-rt==5.1.0
      - toolz==0.12.0
      - tqdm==4.65.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - werkzeug==2.3.6
      - wrapt==1.14.1
      - zipp==3.15.0
